### ISSUE TITLE
install

### ISSUE THREAD

**Issue by Stepan5024** [Stepan5024/EyeGazeFrameworkDemo#1]
(env) C:\Users\user\Documents\EyeGazeFrameworkDemo>python server.py
Traceback (most recent call last):
  File "C:\Users\user\Documents\EyeGazeFrameworkDemo\server.py", line 11, in <module>
    import torch
  File "C:\Users\user\Documents\EyeGazeFrameworkDemo\env\lib\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] Не найден указанный модуль. Error loading "C:\Users\user\Documents\EyeGazeFrameworkDemo\env\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by Stepan5024** [comment]
solution https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
